name: Sync CI

permissions:
  contents: write

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 0 10 * * *

jobs:
  sync:
    name: Sync Fork
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v5
      - name: Sync Upstream Repository
        run: gh repo sync fobe-projects/micropython --source micropython/micropython
